### PR TITLE
[FIZZ-55] Add text to track remaining oranges. Fixed positioning of UI texts.

### LINKED ISSUE #55: Add text to track remaining oranges
- [ ] Add text to ui canvas
- [ ] Print remaining oranges on plate by counting number of child gameobjects in parent particle object

Depends on #56

### PR DESCRIPTION
**Pull request by VonRiecken**
Resolves #55

### CODE REVIEW

File: project-fizz/Assets/Scripts/UI/NumberRemainingOranges.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    {
+        oranges = GameObject.Find("Oranges");    
+        orangeNumberDisplay = GetComponent<Text>();    
+    }
+
+    // Update is called once per frame
+    void Update()
+    {
+        // Debug only shows in console?
+        Debug.Log(oranges.name + " has " + oranges.transform.childCount + " children");
```
Comment (NDGogo) [inline project-fizz/Assets/Scripts/UI/NumberRemainingOranges.cs:26]: Can remove this line

**Review by NDGogo — APPROVED** [review]

File: project-fizz/Assets/Scripts/UI/NumberRemainingOranges.cs (hunk 1 above)
Comment (VonRiecken) [reply project-fizz/Assets/Scripts/UI/NumberRemainingOranges.cs]: Fixed and tidied

**Review by jjbdlsantos — APPROVED** [review]
